# Configuration for a plugin published to npm
[[plugins]]
 package = "@netlify/plugin-lighthouse"
 
  [[plugins.inputs.audits]]
    output_path="reports/index.html"
    path = "index.html" #la racine du site

  [[plugins.inputs.audits]]
    output_path = "reports/frise.html"
    path = "FR/frise.html" #le chemin du fichier à tester
